USE [master];
 
GO
 
If NOT EXISTS (SELECT * FROM sys.server_audits
               WHERE [name] = 'ApplicationEventLogAudits')
    CREATE SERVER AUDIT [ApplicationEventLogAudits]
    TO APPLICATION_LOG
    WITH    (   QUEUE_DELAY = 1000
            , ON_FAILURE = CONTINUE );
 
GO
 
If NOT EXISTS (SELECT * FROM sys.server_audit_specifications
               WHERE [name] = 'ServerApplicationEventLogAudits')
    CREATE SERVER AUDIT SPECIFICATION [ServerApplicationEventLogAudits]
    FOR SERVER AUDIT [ApplicationEventLogAudits]
  ADD (AUDIT_CHANGE_GROUP),
  ADD (BACKUP_RESTORE_GROUP),
  ADD (BROKER_LOGIN_GROUP),
  ADD (DATABASE_CHANGE_GROUP),
  --ADD (DATABASE_OPERATION_GROUP), -- too much noise
  ADD (DATABASE_MIRRORING_LOGIN_GROUP),
  --ADD (DATABASE_OBJECT_ACCESS_GROUP), -- too much noise
  --ADD (DATABASE_OBJECT_CHANGE_GROUP), -- too much noise
  ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),
  ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
  ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
  ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
  --ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP), -- too much noise
  ADD (DATABASE_PERMISSION_CHANGE_GROUP),
  ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
  --ADD (DBCC_GROUP), -- too much noise
  ADD (FAILED_LOGIN_GROUP),
  ADD (LOGIN_CHANGE_PASSWORD_GROUP),
  --ADD (LOGOUT_GROUP), -- too much noise
  --ADD (SCHEMA_OBJECT_ACCESS_GROUP), -- too much noise
  --ADD (SCHEMA_OBJECT_CHANGE_GROUP), -- too much noise
  ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP),
  ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
  ADD (SERVER_OBJECT_CHANGE_GROUP),
  ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP),
  ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP),
  --ADD (SERVER_OPERATION_GROUP), -- too much noise
  ADD (SERVER_PERMISSION_CHANGE_GROUP),
  ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
  --ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP), -- too much noise
  ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
  ADD (SERVER_STATE_CHANGE_GROUP),
  --ADD (SUCCESSFUL_LOGIN_GROUP), -- too much noise
  ADD (TRACE_CHANGE_GROUP)
  WITH (STATE = OFF)
 
GO
 
ALTER SERVER AUDIT SPECIFICATION [ServerApplicationEventLogAudits]
 WITH (STATE = ON)
 
GO
 
ALTER SERVER AUDIT  [ApplicationEventLogAudits]
 WITH (STATE = ON)
 
GO

